-- V16__update_payment_method_enum.sql


ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'PAYSTACK_CARD';
ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'PAYSTACK_BANK_TRANSFER';
ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'PAYSTACK_USSD';
ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'FLUTTERWAVE_CARD';
ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'FLUTTERWAVE_BANK_TRANSFER';
ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'FLUTTERWAVE_MOBILE_MONEY';
ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'STRIPE_CARD';
ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'STRIPE_APPLE_PAY';
ALTER TYPE payment_method ADD VALUE IF NOT EXISTS 'STRIPE_GOOGLE_PAY';

ALTER TABLE payments
    ALTER COLUMN payment_method TYPE payment_method
    USING payment_method::text::payment_method;
